[package]
name = "game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.9.3"
keyframe = "1.1.1"
keyframe_derive = "1.0.0"
num-derive = "0.4.1"
num-traits = "0.2.17"
rand = "0.8.5"
